# Site settings
title: Shaun McGeever
email: ShaunMcGeever@gmail.com
description: "Still working this out..."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
