# Site settings
title: Shaun McGeever
email: ShaunMcGeever@gmail.com
username: ShaunMcGeever
description: ""
baseurl: ""
url: "http://shaunmcgeever.com"

# Build settings
markdown: kramdown
permalink: pretty
